### ISSUE TITLE
`single_mut()` intead of `iter_mut()`

### ISSUE THREAD

**Issue by interacsion** [alilee/snake#10]
This doesn't look safe.
https://github.com/alilee/snake/blob/3b0e2ce11bb1a73e7ae01b12206c13a2d3ffe428/src/input.rs#L16

**Comment by alilee** [comment]
Yeah at the moment this will panic if there are two moving things, but then, it's probably ok considering we only handle input for one - will loop back on future steps. Eventually, this is should drain inputs and send the right keys to the right heads. `for` each  snake isn't going to work in any case.
